# Generated by Django 5.2.8 on 2025-12-22 18:54

import core.services.file_service
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Daewoo', 'Daewoo'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Mercedes‑Benz', 'Mercedes‑Benz'), ('Audi', 'Audi'), ('Mazda', 'Mazda'), ('Renault', 'Renault'), ('Suzuki', 'Suzuki'), ('Skoda', 'Skoda'), ('Peugeot', 'Peugeot'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla')], default='Toyota', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=core.services.file_service.upload_car_photo)),
                ('year', models.PositiveIntegerField(default=1990)),
                ('mileage', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], max_length=3)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
                ('max_speed', models.PositiveIntegerField(default=1, help_text='Max speed km/h')),
                ('seats_count', models.PositiveIntegerField(default=1, help_text='Number of seats')),
                ('engine_volume', models.DecimalField(decimal_places=1, default=1, help_text='Engine vol/l', max_digits=3)),
                ('has_air_conditioner', models.BooleanField(default=False, help_text='Conditioning')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], help_text='Fuel type', max_length=20)),
                ('location', models.CharField(choices=[('Vinnytsia region', 'Vinnytsia region'), ('Volyn region', 'Volyn region'), ('Dnipropetrovsk region', 'Dnipropetrovsk region'), ('Donetsk region', 'Donetsk region'), ('Zhytomyr region', 'Zhytomyr region'), ('Zakarpattia region', 'Zakarpattia region'), ('Zaporizhzhia region', 'Zaporizhzhia region'), ('Ivano-Frankivsk region', 'Ivano-Frankivsk region'), ('Kyiv', 'Kyiv'), ('Kyiv region', 'Kyiv region'), ('Kirovohrad region', 'Kirovohrad region'), ('Luhansk region', 'Luhansk region'), ('Lviv region', 'Lviv region'), ('Mykolaiv region', 'Mykolaiv region'), ('Odesa region', 'Odesa region'), ('Poltava region', 'Poltava region'), ('Rivne region', 'Rivne region'), ('Sumy region', 'Sumy region'), ('Ternopil region', 'Ternopil region'), ('Kharkiv region', 'Kharkiv region'), ('Kherson region', 'Kherson region'), ('Khmelnytskyi region', 'Khmelnytskyi region'), ('Cherkasy region', 'Cherkasy region'), ('Chernivtsi region', 'Chernivtsi region'), ('Chernihiv region', 'Chernihiv region')], max_length=50)),
                ('description', models.TextField(default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('daily_views', models.PositiveIntegerField(default=0)),
                ('weekly_views', models.PositiveIntegerField(default=0)),
                ('monthly_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_attempts', models.PositiveIntegerField(default=0)),
                ('exchange_rate_id', models.CharField(default='', help_text='ID or source of the exchange rate', max_length=50)),
                ('last_exchange_update', models.DateField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=core.services.file_service.upload_car_photo)),
            ],
            options={
                'db_table': 'car_photos',
            },
        ),
    ]
