# Generated by Django 5.2.8 on 2025-11-06 14:41

import core.services.file_service
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('car_shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{,29}$', 'Only alphanumeric characters are allowed.')])),
                ('price', models.FloatField()),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ingredients', models.JSONField(default=list)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('time_prepared', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to=core.services.file_service.upload_car_photo)),
                # ('car_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_shops.carshopmodel')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
