# Generated by Django 5.2.8 on 2025-11-13 21:03

import core.services.file_service
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=core.services.file_service.upload_car_photo)),
            ],
            options={
                'db_table': 'car_shops',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='size',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='time_prepared',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Daewoo', 'Daewoo'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Mercedes‑Benz', 'Mercedes‑Benz'), ('Audi', 'Audi'), ('Mazda', 'Mazda'), ('Renault', 'Renault'), ('Suzuki', 'Suzuki'), ('Skoda', 'Skoda'), ('Peugeot', 'Peugeot'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla')], default='Toyota', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], default='UAH', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='daily_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='edit_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Engine vol/l', max_digits=3),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='exchange_rate_id',
            field=models.CharField(default='', help_text='ID or source of the exchange rate', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='diesel', help_text='Fuel type', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='has_air_conditioner',
            field=models.BooleanField(default=False, help_text='Conditioning'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='last_exchange_update',
            field=models.DateField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='location',
            field=models.CharField(choices=[('Vinnytsia region', 'Vinnytsia region'), ('Volyn region', 'Volyn region'), ('Dnipropetrovsk region', 'Dnipropetrovsk region'), ('Donetsk region', 'Donetsk region'), ('Zhytomyr region', 'Zhytomyr region'), ('Zakarpattia region', 'Zakarpattia region'), ('Zaporizhzhia region', 'Zaporizhzhia region'), ('Ivano-Frankivsk region', 'Ivano-Frankivsk region'), ('Kyiv', 'Kyiv'), ('Kyiv region', 'Kyiv region'), ('Kirovohrad region', 'Kirovohrad region'), ('Luhansk region', 'Luhansk region'), ('Lviv region', 'Lviv region'), ('Mykolaiv region', 'Mykolaiv region'), ('Odesa region', 'Odesa region'), ('Poltava region', 'Poltava region'), ('Rivne region', 'Rivne region'), ('Sumy region', 'Sumy region'), ('Ternopil region', 'Ternopil region'), ('Kharkiv region', 'Kharkiv region'), ('Kherson region', 'Kherson region'), ('Khmelnytskyi region', 'Khmelnytskyi region'), ('Cherkasy region', 'Cherkasy region'), ('Chernivtsi region', 'Chernivtsi region'), ('Chernihiv region', 'Chernihiv region')], default='Kyiv', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='max_speed',
            field=models.PositiveIntegerField(default=1, help_text='Max speed km/h'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='mileage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='monthly_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='seats_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of seats'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='weekly_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(default=1990),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
