# Generated by Django 5.2.8 on 2025-11-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carphoto_remove_carmodel_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carphoto',
            options={},
        ),
    ]
