# Generated by Django 5.2.8 on 2025-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Daewoo', 'Daewoo'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Mercedes‑Benz', 'Mercedes‑Benz'), ('Audi', 'Audi'), ('Mazda', 'Mazda'), ('Renault', 'Renault'), ('Suzuki', 'Suzuki'), ('Skoda', 'Skoda'), ('Peugeot', 'Peugeot'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla')], default='Toyota', max_length=50),
        ),
    ]
