# Generated by Django 5.2.8 on 2025-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_create_carphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=20, null=True),
        ),
    ]
