# Generated by Django 5.2.8 on 2026-01-07 11:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, help_text='Engine vol/l', max_digits=4),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='last_exchange_update',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='max_speed',
            field=models.PositiveIntegerField(help_text='Max speed km/h'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats_count',
            field=models.PositiveIntegerField(help_text='Number of seats'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
