# Generated by Django 5.2.8 on 2026-01-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_carmodel_engine_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='exchange_rate_id',
            field=models.CharField(blank=True, default='', help_text='ID or source of the exchange rate', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='last_exchange_update',
            field=models.DateField(blank=True, default=0, null=True),
        ),
    ]
