# Generated by Django 5.2.7 on 2025-10-12 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carmodel_day_alter_carmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{,29}$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
