# Generated by Django 5.2.7 on 2025-10-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_carmodel_name_alter_carmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
