# Generated by Django 5.2.7 on 2025-10-28 18:43

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_car_photo),
        ),
    ]
