import type { Metadata } from "next";
import React, {Suspense} from "react";
import {ThemeProvider} from "next-themes";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import MenuComponent from "@/components/menu-component/MenuComponent";
import {LoaderComponent} from "@/components/loader-component/LoaderComponent";

const openSans = Open_Sans({
    subsets: ["latin"],
    weight: ["400", "600"],
});

export const metadata: Metadata = {
    title: "Turbo Horse",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "/favicon/favicon-32x32.png", sizes: "32x32", type: "image/png" },
            { url: "/favicon/favicon-16x16.png", sizes: "16x16", type: "image/png" },
        ],
        apple: "/favicon/apple-touch-icon.png",
    }};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={openSans.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
        >
         <Suspense fallback={<LoaderComponent />}>
            <MenuComponent />
          </Suspense>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}