# Generated by Django 5.2.7 on 2025-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profilemodel_avatar_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
