# Generated by Django 5.2.7 on 2025-11-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profilemodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_active',
        ),
    ]
